{
 "title": "Logs / App",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" },
   {
    "name": "app",
    "label": "Application",
    "query": "label_values({namespace=\"$namespace\"}, app)"
   },
   {
    "name": "logLevel",
    "label": "Log Level",
    "query": "Error,Warning,Info,Debug,Critical,Severe\n"
   },
   { "name": "search", "label": "Search" }
  ]
 },
 "panels": [
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", app=\"$app\"} |~ \"(?i)$logLevel\""
    }
   ]
  },
  {
   "title": "Log Volume Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", app=\"$app\"} [$__interval]))"
    }
   ]
  },
  {
   "title": "Log Level Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (level) (count_over_time({namespace=\"$namespace\", app=\"$app\"} \r\n| logfmt \r\n| level != \"\"\r\n| __error__=\"\" [$__interval]))"
    }
   ]
  }
 ]
}