---
- name: Wait for Homepage deployment to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: Deployment
    name: homepage
    namespace: apps
  register: homepage_deployment
  until:
    - homepage_deployment.resources is defined
    - homepage_deployment.resources | length > 0
    - homepage_deployment.resources[0].status.readyReplicas is defined
    - homepage_deployment.resources[0].status.readyReplicas > 0
  retries: 30
  delay: 10
  when: deploy_homepage | bool

- name: Get current Homepage pod (with retry)
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: apps
    label_selectors:
      - app.kubernetes.io/name=homepage
    field_selectors:
      - status.phase=Running
  register: homepage_pod
  until:
    - homepage_pod.resources is defined
    - homepage_pod.resources | length > 0
    - homepage_pod.resources[0].status.phase == "Running"
    - homepage_pod.resources[0].status.containerStatuses is defined
    - homepage_pod.resources[0].status.containerStatuses | length > 0
    - homepage_pod.resources[0].status.containerStatuses[0].ready == true
  retries: 10
  delay: 5
  when: deploy_homepage | bool

- name: Install python3 kubernetes on localhost
  ansible.builtin.apt:
    name: python3-kubernetes
    state: present
  delegate_to: localhost
  when: deploy_homepage | bool
  run_once: true

- name: Debug pod information
  ansible.builtin.debug:
    msg: 
      - "Found pod: {{ homepage_pod.resources[0].metadata.name }}"
      - "Pod status: {{ homepage_pod.resources[0].status.phase }}"
      - "Container ready: {{ homepage_pod.resources[0].status.containerStatuses[0].ready }}"
  when: 
    - deploy_homepage | bool
    - homepage_pod.resources is defined
    - homepage_pod.resources | length > 0

- name: Copy icons to pod with retry
  kubernetes.core.k8s_cp:
    namespace: apps
    pod: "{{ current_pod.metadata.name }}"
    local_path: "{{ role_path }}/homepage/icons"
    remote_path: "/app/public/"
    state: to_pod
  delegate_to: localhost
  vars:
    current_pod: "{{ homepage_pod.resources[0] }}"
  when:
    - deploy_homepage | bool
    - homepage_pod.resources is defined
    - homepage_pod.resources | length > 0
  register: icons_copy_result
  retries: 3
  delay: 5
  until: icons_copy_result is succeeded

- name: Restart Homepage deployment if new icons were added
  kubernetes.core.k8s:
    state: patched
    kind: Deployment
    name: homepage
    namespace: apps
    definition:
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{ ansible_date_time.iso8601 }}"
  when:
    - deploy_homepage | bool
    - icons_copy_result is succeeded
    - icons_copy_result is changed