---
- name: Configure External Storage for Kubernetes Cluster
  when: external_storage.enabled | default(false) | bool
  block:
    - name: Create namespace for storage classes
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: external-storage
            labels:
              app.kubernetes.io/name: external-storage
              app.kubernetes.io/part-of: cluster-storage

    # SMB configuration
    - name: Install SMB CSI Driver
      kubernetes.core.helm:
        name: csi-driver-smb
        chart_ref: csi-driver-smb
        chart_repo_url: https://raw.githubusercontent.com/kubernetes-csi/csi-driver-smb/master/charts
        chart_version: "v1.18.0"
        release_namespace: kube-system
        values:
          image:
            csiProvisioner:
              repository: registry.k8s.io/sig-storage/csi-provisioner
              tag: v5.0.1
            csiAttacher:
              repository: registry.k8s.io/sig-storage/csi-attacher 
              tag: v4.6.1
            csiResizer:
              repository: registry.k8s.io/sig-storage/csi-resizer
              tag: v1.11.1
            livenessProbe:
              repository: registry.k8s.io/sig-storage/livenessprobe
              tag: v2.13.1
            nodeDriverRegistrar:
              repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
              tag: v2.11.1
            smb:
              repository: registry.k8s.io/sig-storage/smbplugin
              tag: v1.18.0
      when: external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('type', 'equalto', 'smb') | list | length > 0

    - name: Store SMB credentials in secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ item.name }}-secret"
            namespace: external-storage
          type: Opaque
          stringData:
            username: "{{ item.smb.user }}"
            password: "{{ item.smb.password }}"
      loop: "{{ external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('type', 'equalto', 'smb') | list }}"
      loop_control:
        label: "{{ item.name }}"
      when: external_storage.nas | selectattr('type', 'equalto', 'smb') | list | length > 0

    # NFS configuration
    - name: Install NFS CSI Driver
      kubernetes.core.helm:
        name: nfs-subdir-external-provisioner
        chart_ref: nfs-subdir-external-provisioner
        chart_repo_url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
        chart_version: "4.0.17"
        release_namespace: kube-system
        values:
          nfs:
            server: "{{ external_storage.nas | selectattr('type', 'equalto', 'nfs') | map(attribute='server') | first | default('') }}"
            path: "{{ external_storage.nas | selectattr('type', 'equalto', 'nfs') | map(attribute='nfs.path') | first | default('') }}"
      when: external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('type', 'equalto', 'nfs') | list | length > 0

    # Create storage classes - separated by type
    - name: Delete existing SMB Storage Classes to recreate with correct parameters
      kubernetes.core.k8s:
        state: absent
        api_version: storage.k8s.io/v1
        kind: StorageClass
        name: "{{ item.storage_class }}"
      loop: "{{ external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('type', 'equalto', 'smb') | list }}"
      loop_control:
        label: "{{ item.name }}"
      when: external_storage.nas | selectattr('type', 'equalto', 'smb') | list | length > 0
      ignore_errors: true

    - name: Wait for SMB StorageClass deletion
      ansible.builtin.pause:
        seconds: 5
      when: external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('type', 'equalto', 'smb') | list | length > 0

    - name: Create Storage Classes for SMB
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: "{{ item.storage_class }}"
            labels:
              storage-type: smb
          provisioner: "smb.csi.k8s.io"
          reclaimPolicy: "{{ item.reclaim_policy | default('Retain') }}"
          volumeBindingMode: Immediate
          parameters:
            source: "//{{ item.server }}/{{ item.smb.share }}"
            csi.storage.k8s.io/node-stage-secret-name: "{{ item.name }}-secret"
            csi.storage.k8s.io/node-stage-secret-namespace: "external-storage"
            csi.storage.k8s.io/provisioner-secret-name: "{{ item.name }}-secret"
            csi.storage.k8s.io/provisioner-secret-namespace: "external-storage"
      loop: "{{ external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('type', 'equalto', 'smb') | list }}"
      loop_control:
        label: "{{ item.name }}"
      when: external_storage.nas | selectattr('type', 'equalto', 'smb') | list | length > 0

    - name: Create Storage Classes for NFS
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: storage.k8s.io/v1
          kind: StorageClass
          metadata:
            name: "{{ item.storage_class }}"
            labels:
              storage-type: nfs
          provisioner: "nfs-client"
          reclaimPolicy: "{{ item.reclaim_policy | default('Retain') }}"
          volumeBindingMode: Immediate
          parameters:
            server: "{{ item.server }}"
            path: "{{ item.nfs.path }}"
            mountOptions: "{{ item.nfs.mount_options | default('nfsvers=4.1') }}"
      loop: "{{ external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('type', 'equalto', 'nfs') | list }}"
      loop_control:
        label: "{{ item.name }}"
      when: external_storage.nas | selectattr('type', 'equalto', 'nfs') | list | length > 0

    - name: Create namespaces for applications that need external storage
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: "{{ item.value.namespace | default(item.key) }}"
            labels:
              app.kubernetes.io/name: "{{ item.key }}"
              app.kubernetes.io/part-of: external-storage
      loop: "{{ external_storage.applications | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      when: item.value.enabled | bool

    # Create PVCs for applications
    - name: Create PVCs for Applications (SMB/NFS)
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: PersistentVolumeClaim
          metadata:
            name: "{{ item.key }}-data"
            namespace: "{{ item.value.namespace | default(item.key) }}"
            labels:
              app: "{{ item.key }}"
              storage-type: "{{ external_storage.nas | selectattr('name', 'equalto', item.value.storage_name) | map(attribute='type') | first }}"
          spec:
            accessModes:
              - "{{ external_storage.nas | selectattr('name', 'equalto', item.value.storage_name) | map(attribute='access_mode') | first | default('ReadWriteMany') }}"
            storageClassName: "{{ external_storage.nas | selectattr('name', 'equalto', item.value.storage_name) | map(attribute='storage_class') | first }}"
            resources:
              requests:
                storage: "{{ item.value.size }}"
      loop: "{{ external_storage.applications | dict2items }}"
      loop_control:
        label: "{{ item.key }}"
      vars:
        matching_storage: "{{ external_storage.nas | selectattr('enabled', 'equalto', true) | selectattr('name', 'equalto', item.value.storage_name) | list }}"
      when:
        - item.value.enabled | bool
        - matching_storage | length > 0
        - matching_storage[0].type in ['smb', 'nfs']
