---

- import_tasks: homepage.yml
  tags:
    - apps
    - apps:homepage

# - import_tasks: homeassistant.yml
#   tags:
#     - apps
#     - apps:homeassistant
#     - apps:smarthome

- import_tasks: tailscale.yml
  tags:
    - apps
    - apps:tailscale

